In [1]:
from CryptowatchDataGetter import CryptowatchDataGetter as cdg

cdg.get_and_add_to_csv()
#cdg.check_csv_data()

In [2]:
import pandas as pd
df = pd.read_csv('one_min_data.csv')

In [4]:
df = df.drop(['Unnamed: 0'],axis=1)

In [6]:
df.to_csv('one_min_data2.csv', index=False)

In [9]:
dff = pd.read_csv('one_min_data.csv')

TypeError: parser_f() got an unexpected keyword argument 'index'

In [8]:
dff

,unix_time,dt,open,high,low,close,size
0,1552644960,2019-03-15 19:16:00,427506,427647,427489,427514,155.148102
1,1552645020,2019-03-15 19:17:00,427503,427559,427479,427509,104.366502
2,1552645080,2019-03-15 19:18:00,427509,427541,427420,427529,84.129965
3,1552645140,2019-03-15 19:19:00,427528,427640,427499,427603,57.839793
4,1552645200,2019-03-15 19:20:00,427613,427640,427554,427575,49.985649
5,1552645260,2019-03-15 19:21:00,427580,427613,427511,427515,50.689969
6,1552645320,2019-03-15 19:22:00,427524,427525,427454,427485,55.643145
7,1552645380,2019-03-15 19:23:00,427495,427551,427320,427500,69.310931
8,1552645440,2019-03-15 19:24:00,427493,427504,427230,427452,184.988910
9,1552645500,2019-03-15 19:25:00,427445,427532,427419,427472,146.177223
10,1552645560,2019-03-15 19:26:00,427488,427516,427400,427407,70.783274
11,1552645620,2019-03-15 19:27:00,427425,427500,427417,427492,53.514246
12,1552645680,2019-03-15 19:28:00,427492,427527,427466,427510,62.342705
13,1552645740,2019-03-15 19:29:00,427502,427543,427469,427511,52.257241
14,1552645800,2019-03-15 19:30:00,427511,427662,427451,427567,117.632879
15,1552645860,2019-03-15 19:31:00,427594,427650,427533,427601,61.331920
16,1552645920,2019-03-15 19:32:00,427598,427776,427594,427701,166.795941
17,1552645980,2019-03-15 19:33:00,427707,427756,427650,427652,76.750309
18,1552646040,2019-03-15 19:34:00,427677,427771,427650,427755,77.867394
19,1552646100,2019-03-15 19:35:00,427762,427820,427732,427762,83.529059
20,1552646160,2019-03-15 19:36:00,427743,427840,427734,427809,130.033252
21,1552646220,2019-03-15 19:37:00,427793,427826,427710,427782,97.463393
22,1552646280,2019-03-15 19:38:00,427783,427980,427713,427938,180.430171
23,1552646340,2019-03-15 19:39:00,427937,427972,427851,427930,108.860324
24,1552646400,2019-03-15 19:40:00,427901,427931,427800,427875,91.961941
25,1552646460,2019-03-15 19:41:00,427881,427888,427760,427794,54.369708
26,1552646520,2019-03-15 19:42:00,427795,427885,427739,427819,137.795529
27,1552646580,2019-03-15 19:43:00,427813,427912,427803,427912,119.402361
28,1552646640,2019-03-15 19:44:00,427912,427946,427860,427901,102.061175
29,1552646700,2019-03-15 19:45:00,427902,428124,427873,428017,171.533125
...,...,...,...,...,...,...,...
5970,1553005800,2019-03-19 23:30:00,440311,440451,440245,440294,145.816119
5971,1553005860,2019-03-19 23:31:00,440288,440474,440249,440434,160.783669
5972,1553005920,2019-03-19 23:32:00,440434,440597,440426,440540,242.011780
5973,1553005980,2019-03-19 23:33:00,440540,440780,440501,440737,361.024522
5974,1553006040,2019-03-19 23:34:00,440737,440859,440731,440736,301.263277
5975,1553006100,2019-03-19 23:35:00,440723,440900,440690,440900,197.016351
5976,1553006160,2019-03-19 23:36:00,440900,441018,440816,441018,240.937939
5977,1553006220,2019-03-19 23:37:00,441051,441220,441000,441125,280.276695
5978,1553006280,2019-03-19 23:38:00,441125,441256,441021,441021,258.546642
5979,1553006340,2019-03-19 23:39:00,441031,441234,440822,441231,276.729706
5980,1553006400,2019-03-19 23:40:00,441234,441380,441180,441344,347.020991
5981,1553006460,2019-03-19 23:41:00,441285,441740,441010,441100,679.632765
5982,1553006520,2019-03-19 23:42:00,441084,441480,441044,441185,413.126090
5983,1553006580,2019-03-19 23:43:00,441185,441234,440746,440890,456.671776
5984,1553006640,2019-03-19 23:44:00,440970,440998,440805,440897,326.443203
5985,1553006700,2019-03-19 23:45:00,440900,441092,440678,440678,411.349657
5986,1553006760,2019-03-19 23:46:00,440678,440709,440000,440276,544.321217
5987,1553006820,2019-03-19 23:47:00,440146,440195,439393,439891,598.607014
5988,1553006880,2019-03-19 23:48:00,439891,439999,439500,439500,364.732305
5989,1553006940,2019-03-19 23:49:00,439500,439590,438813,438951,804.596991
5990,1553007000,2019-03-19 23:50:00,439014,439507,438265,439211,907.793808
5991,1553007060,2019-03-19 23:51:00,439316,439611,439181,439538,536.610426
5992,1553007120,2019-03-19 23:52:00,439487,439549,438414,438948,623.294675
5993,1553007180,2019-03-19 23:53:00,438948,439332,438818,438958,412.620049
5994,1553007240,2019-03-19 23:54:00,438846,439191,438801,438924,352.991336
5995,1553007300,2019-03-19 23:55:00,438924,439230,438920,439123,217.544542
5996,1553007360,2019-03-19 23:56:00,439084,439197,438605,439015,255.478899
5997,1553007420,2019-03-19 23:57:00,438887,439200,438772,439133,305.918290
5998,1553007480,2019-03-19 23:58:00,439138,439488,439067,439295,359.972571
5999,1553007540,2019-03-19 23:59:00,439308,439547,439295,439476,343.597194